'use client';
import { useState, useEffect } from 'react';
import Sidebar from '../../components/Sidebar';
import AuthGuard from '../../components/AuthGuard';
import { fetchPendingApprovalsFull, processApprovalAction, getUser } from '@/lib/api';

export default function AdminApprovalsPage() {
  const [user, setUser] = useState(null);
  const [approvals, setApprovals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [processing, setProcessing] = useState(null); // stores ID of approval being processed
  const [message, setMessage] = useState({ type: '', text: '' });

  useEffect(() => {
    setUser(getUser());
    loadApprovals();
  }, []);

  const loadApprovals = async () => {
    try {
      setLoading(true);
      const data = await fetchPendingApprovalsFull();
      setApprovals(data);
    } catch (err) {
      console.error('Error loading approvals:', err);
      setMessage({ type: 'error', text: err.message });
    } finally {
      setLoading(false);
    }
  };

  const handleDecision = async (id, decision) => {
    try {
      setProcessing(id);
      setMessage({ type: '', text: '' });
      await processApprovalAction(id, decision);
      
      setMessage({ type: 'success', text: `Approval request ${decision} successfully!` });
      // Remove the processed approval from the UI
      setApprovals((prev) => prev.filter((a) => a.id !== id));
    } catch (err) {
      setMessage({ type: 'error', text: err.message });
    } finally {
      setProcessing(null);
    }
  };

  return (
    <AuthGuard>
      <div className="flex h-screen bg-background overflow-hidden">
        <Sidebar />
        
        <main className="flex-1 ml-0 md:ml-64 overflow-y-auto pt-16 md:pt-0 p-lg">
          <div className="max-w-5xl mx-auto space-y-xl">
            {/* Header Banner */}
            <div className="bg-gradient-to-br from-surface-container-highest to-surface-container border border-outline-variant rounded-2xl p-xl shadow-sm relative overflow-hidden">
              <div className="absolute -right-10 -top-10 text-9xl text-primary/5 select-none pointer-events-none">
                <span className="material-symbols-outlined">fact_check</span>
              </div>
              
              <div className="relative z-10">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary-container/30 border border-primary/20 text-primary font-label-sm text-label-sm uppercase tracking-wider font-bold mb-4">
                  <span className="material-symbols-outlined text-sm">shield</span>
                  High-Risk Actions
                </div>
                <h1 className="font-display-sm text-display-sm font-extrabold text-on-surface mb-2 tracking-tight">
                  Human Approvals Queue
                </h1>
                <p className="font-body-lg text-body-lg text-on-surface-variant max-w-2xl">
                  Review and authorize pending high-risk tool calls (e.g., Refunds) generated by the AI agent.
                </p>
              </div>
            </div>

            {message.text && (
              <div className={`p-4 rounded-xl border ${message.type === 'error' ? 'bg-error-container/20 text-error border-error/30' : 'bg-primary-container/20 text-primary border-primary/30'}`}>
                {message.text}
              </div>
            )}

            <div className="space-y-md">
              <h2 className="font-title-lg text-title-lg font-bold text-on-surface">Pending Requests ({approvals.length})</h2>
              
              {loading ? (
                <div className="flex items-center justify-center p-xl">
                  <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full"></div>
                </div>
              ) : approvals.length === 0 ? (
                <div className="bg-surface-container-lowest border border-outline-variant border-dashed rounded-2xl p-xl text-center">
                  <span className="material-symbols-outlined text-4xl text-outline mb-2">done_all</span>
                  <h3 className="font-title-md text-title-md font-bold text-on-surface">All Caught Up</h3>
                  <p className="text-on-surface-variant">There are no pending approval requests at this time.</p>
                </div>
              ) : (
                <div className="grid gap-lg">
                  {approvals.map((req) => {
                    const payload = typeof req.action_payload === 'string' 
                      ? JSON.parse(req.action_payload) 
                      : req.action_payload || {};
                      
                    return (
                      <div key={req.id} className="bg-surface border border-outline-variant rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-shadow">
                        <div className="bg-surface-container-lowest border-b border-outline-variant p-md flex items-center justify-between">
                          <div className="flex items-center gap-3">
                            <span className="material-symbols-outlined text-error">warning</span>
                            <div>
                              <h3 className="font-title-md text-title-md font-bold text-on-surface">
                                {req.action_type === 'submit_refund_request' ? 'Refund Request' : req.action_type}
                              </h3>
                              <p className="font-label-sm text-label-sm text-on-surface-variant">ID: {req.id} • Created: {new Date(req.created_at).toLocaleString()}</p>
                            </div>
                          </div>
                        </div>
                        
                        <div className="p-md grid grid-cols-1 md:grid-cols-2 gap-lg">
                          <div className="space-y-sm">
                            <h4 className="font-label-md text-label-md uppercase tracking-wider text-on-surface-variant font-bold">Customer Details</h4>
                            <div className="bg-surface-container p-sm rounded-lg">
                              <p><span className="font-semibold">Name:</span> {payload.userName || 'N/A'}</p>
                              <p><span className="font-semibold">Email:</span> {payload.userEmail || 'N/A'}</p>
                            </div>
                            
                            <h4 className="font-label-md text-label-md uppercase tracking-wider text-on-surface-variant font-bold mt-md">Request Reason</h4>
                            <div className="bg-surface-container p-sm rounded-lg">
                              <p className="italic">"{payload.userRequest || 'No reason provided'}"</p>
                            </div>
                          </div>
                          
                          <div className="space-y-sm">
                            <h4 className="font-label-md text-label-md uppercase tracking-wider text-on-surface-variant font-bold">Order Information</h4>
                            <div className="bg-surface-container p-sm rounded-lg h-full">
                              <p><span className="font-semibold">Order ID:</span> {payload.orderId || 'N/A'}</p>
                              <div className="mt-2 text-sm text-on-surface-variant break-words">
                                {payload.orderDetails || 'No details available'}
                              </div>
                            </div>
                          </div>
                        </div>
                        
                        <div className="bg-surface-container-lowest border-t border-outline-variant p-md flex gap-4 justify-end">
                          <button
                            onClick={() => handleDecision(req.id, 'rejected')}
                            disabled={processing === req.id}
                            className="px-6 py-2 rounded-lg font-bold text-error bg-error-container/20 border border-error/30 hover:bg-error-container/40 transition-colors"
                          >
                            Reject
                          </button>
                          <button
                            onClick={() => handleDecision(req.id, 'approved')}
                            disabled={processing === req.id}
                            className="px-6 py-2 rounded-lg font-bold text-on-primary bg-primary hover:bg-primary/90 transition-colors shadow-sm"
                          >
                            {processing === req.id ? 'Processing...' : 'Approve Refund'}
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </main>
      </div>
    </AuthGuard>
  );
}
