/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#581e00",
        "on-secondary-container": "#b3b1ff",
        "surface-variant": "#343535",
        "surface-container-lowest": "#0d0e0f",
        "tertiary-fixed": "#ffdbcd",
        "surface": "#121414",
        "on-error": "#690005",
        "on-primary-container": "#ffffff",
        "secondary-fixed-dim": "#c3c0ff",
        "error": "#ffb4ab",
        "secondary-fixed": "#e2dfff",
        "secondary": "#c3c0ff",
        "primary-fixed-dim": "#aec6ff",
        "surface-container-high": "#292a2a",
        "surface-container-low": "#1b1c1c",
        "on-tertiary-container": "#fffeff",
        "on-tertiary-fixed": "#360f00",
        "surface-container": "#1f2020",
        "background": "#121414",
        "tertiary": "#ffb596",
        "surface-dim": "#121414",
        "on-surface": "#e3e2e2",
        "on-background": "#e3e2e2",
        "surface-container-highest": "#343535",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#ca4e00",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-primary-fixed-variant": "#004397",
        "secondary-container": "#3626ce",
        "on-primary-fixed": "#001a43",
        "surface-bright": "#383939",
        "inverse-primary": "#0059c5",
        "inverse-surface": "#e3e2e2",
        "error-container": "#93000a",
        "primary": "#aec6ff",
        "on-surface-variant": "#c1c6d7",
        "outline": "#8b90a0",
        "primary-container": "#0070f3",
        "tertiary-fixed-dim": "#ffb596",
        "outline-variant": "#414754",
        "on-secondary-fixed-variant": "#3323cc",
        "inverse-on-surface": "#303031",
        "on-error-container": "#ffdad6",
        "on-primary": "#002e6b",
        "on-secondary-fixed": "#0f0069",
        "surface-tint": "#aec6ff",
        "on-secondary": "#1d00a5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "xs": "4px",
        "xl": "40px",
        "xxl": "64px",
        "md": "16px",
        "gutter": "24px",
        "lg": "24px",
        "sm": "8px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "mono-sm": ["Geist Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "mono-sm": ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
